###########################################################################
# This is a script to stop the running measurements. To run this script
# Change the API key to the user's API key.
# Args- File containing the list of requests (O/P generated by the
# measurements file.)
###########################################################################
from ripe.atlas.cousteau import AtlasStopRequest
import sys


ATLAS_API_KEY = "f00d3214-a18e-4f6d-8188-104dd1192b36"

# msm_request_list is a list of all the requests. Assuming that there is only one line
# Comma separated (as generated by the measurements script)
with open(sys.argv[1].strip(), "r") as f:
    req_list = f.readline()
req_list = req_list.split(', ')
for req in req_list:
    atlas_request = AtlasStopRequest(msm_id=req.strip(), key=ATLAS_API_KEY)
    (is_success, response) = atlas_request.create()
    if is_success:
        print("Request Id - " + str(req) + "Successfully Stopped!!")
    else:
        print("Error Stopping Request Id - " + str(req))
